version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - IP_ADDR=localhost
      - PORT=8080
      - URL=http://example.com
    volumes:
      - threejsData:/app/api/public
volumes:
  threejsData: